@endpoint = http://localhost:3000/api/v1/budget 

###

POST {{endpoint}} HTTP/3.0
Content-Type: application/json

{
    "name": "Kian R.",
    "email": "kianoreynolds69@gmail.com",
    "password": "Kian1234",
    "category": "Groceries",
    "budgetLimit": 500,
    "transactions": [
        {
            "type": "expense",
            "amount": 50,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        }
        
    ]

}

###

# @name postABudget
POST {{endpoint}} HTTP/1.1
content-type: application/json
//x-api-key: ""

{ 
"name": "Kian",
"email": "kian1@gmail.com",
"password": "password"
}

###
POST http://localhost:3000/api/v1/auth HTTP/1.1
content-type: application/json

{ 
   "name": "Kian",
"email": "kian1@gmail.com",
"password": "password"

}

###
POST {{endpoint}} HTTP/3.0
Content-Type: application/json

{
    "name": "D",
    
}
###









GET {{endpoint}} HTTP/3.0

###

GET {{endpoint}}/67153d1a44ee23ddafa999b3 HTTP/3.0

###

GET {{endpoint}}/67153d1a44ee23ddafa999 HTTP/3.0

###
















PUT {{endpoint}}/67153e5c44ee23ddafa999b4 HTTP/3.0
Content-Type: application/json

{
    "name": "John Wayne Jr",
    "category": "Groceries",
    "budgetLimit": 200,
    "transactions": [
        {
            "type": "expense",
            "amount": 75,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        },
        {
            "type": "expense",
            "amount": 60,
            "date": "2024-10-11",
            "description": "Grocery store purchase"
        },
        {
            "type": "expense",
            "amount": 50,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        },
        {
            "type": "expense",
            "amount": 50,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        },
        {
            "type": "expense",
            "amount": 50,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        },
        {
            "type": "expense",
            "amount": 50,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        },
        {
            "type": "expense",
            "amount": 50,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        }
    ]
}

###
//not found
PUT {{endpoint}} HTTP/3.0
Content-Type: application/json

{
    "name": "John Wayne Jr",
    "category": "Groceries",
    "budgetLimit": 200,
    "transactions": [
        {
            "type": "expense",
            "amount": 50,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        }
    ]
}

###
//invalid
PUT {{endpoint}}/67153e5c44ee23ddafa999 HTTP/3.0
Content-Type: application/json

{
    "name": "John Wayne Jr",
    "category": "Groceries",
    "budgetLimit": 200,
    "transactions": [
        {
            "type": "expense",
            "amount": 50,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        }
        
    ]
}

###








DELETE {{endpoint}}/67153d1a44ee23ddafa999b3 HTTP/3.0

###

DELETE {{endpoint}}/67152b39b51cb85aee197dd HTTP/3.0

###