@endpoint = http://localhost:3000/api/v1/budget 

###

POST {{endpoint}} HTTP/3.0
Content-Type: application/json

{
    "name": "Mr. Reynolds",
    "category": "Groceries",
    "budgetLimit": 200,
    "transactions": [
        {
            "type": "expense",
            "amount": 74,
            "date": "2024-10-10",
            "description": "Supermarket groceries"
        },
        {
            "type": "expense",
            "amount": 30,
            "date": "2024-10-15",
            "description": "Grocery store purchase"
        }
    ]
}

###
GET {{endpoint}} HTTP/3.0

###

PUT {{endpoint}}/67140b09c92b9617aba9c9c1 HTTP/3.0
Content-Type: application/json

{
    "name": "Mr. Reynolds",
    "budgetLimit": 200,
    
}

###

DELETE {{endpoint}}/67140b3bc92b9617aba9c9c2 HTTP/3.0

###