@endpoint = http://localhost:3000/api/v1/users
@gradeHistory = http://localhost:3000/api/v1/gradeHistories
@
###
### POST Request for a contact 
## Expected result is ........
POST {{endpoint}} HTTP/3.0
content-type: application/json

{ "name" : "Monday is here",
"email": "jdoe123@gmail.com"
}
###
# @name postAUser
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: ""

{ "name" : "Monday is here",
"email": "jdoe123@gmail.com"
}
###
@newObjectID = {{postAUser.response.headers.location}}


   GET {{endpoint}}/{{{{newObjectID}}}}

###
PUT http://localhost:3000/api/v1/users/670403a3595adb1ffcd15911
content-type: application/json

{ "name" : "Kian Reynolds",
"email": "kianreynolds234@gmail.com"
}

###
GET {{endpoint}} HTTP/1.1


###





