@endpoint = http://localhost:3000/api/v1/users
@
###
### POST Request for a contact 
## Expected result is ........
POST {{endpoint}} HTTP/3.0
content-type: application/json

{ 
"name" : "Joe",
"email": "joeneill101@gmail.com",
"password": "password",
"role": "user"
}
###
# @name postAUser
POST {{endpoint}} HTTP/1.1
content-type: application/json
//x-api-key: ""

{ 

"email": "joe69@gmail.com",
"password": "password"
}
###
# @newObjectID = {{postAUser.response.headers.location}}


#    GET {{endpoint}}/{{{{newObjectID}}}}

###
PUT http://localhost:3000/api/v1/users/670403a3595adb1ffcd15911
content-type: application/json

{ "name" : "Kian Reynolds",
"email": "kianreynolds234@gmail.com"
}

###
POST http://localhost:3000/api/v1/auth HTTP/1.1
content-type: application/json

{ "name" : "Kian Reynolds",
"email": "kiangreynolds74@gmail.com",
"password": "password"

}
###

POST {{endpoint}} HTTP/3.0
content-type: application/json

{ 
    "name" : "Admin ",
   "email": "adm@gmail.com",
   "password" : "password",
   "role": "admin"
}

### POST Request for a login
## Expected result is a token with a payload that inlcudes a role of admin
# @name loginAdmin
POST http://localhost:3000/api/v1/auth HTTP/3.0
content-type: application/json

{
   "email": "admin@gmail.com",
   "password" : "password"
}

###

POST http://localhost:3000/api/v1/users HTTP/3.0
content-type: application/json

{
    "name": "AdminUser",
   "email": "admin1@gmail.com",
   "password" : "password",
   "role": "admin"
}

###
